# This workflow will run build, test, format, and lint for the project

name: Go

on:
  push:

jobs:

  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.22.4'

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...

    - name: gofmt
      uses: Jerome1337/gofmt-action@v1.0.5
      
    - name: golangci-lint
      uses: golangci/golangci-lint-action@v6